version: '2'

services:
  postgres:
    container_name: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./.envs/.production/.postgres
    expose:
      - 5432

  urlshortener_app:
    container_name: urlshortener-app
    build:
      context: ./urlshortener_app
      dockerfile: ./compose/production/Dockerfile
    restart: always
    env_file:
      - ./.envs/.production/.urlshortener_app
      - ./.envs/.production/.postgres
    command: >
      su -m app_user -c "python wait_for_postgres.py &&
               gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - static_volume:/usr/src/urlshortener/static
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/urlshortener/static
    ports:
      - 8000:8080
    depends_on:
      - urlshortener_app

volumes:
  static_volume:
